BEGIN;
SELECT no_plan();
SELECT has_table('public', 'workspace_invites', 'Convites são persistidos sem usuário fictício');
SELECT has_function('public', 'team_invite', ARRAY['uuid','uuid','text','text','uuid'], 'Convite por RPC');
SELECT has_function('public', 'team_change_role', ARRAY['uuid','uuid','uuid','text'], 'Mudança de papel por RPC');
SELECT has_function('public', 'team_suspend_member', ARRAY['uuid','uuid','uuid'], 'Suspensão por RPC');
SELECT has_function('public', 'team_cancel_invite', ARRAY['uuid','uuid','uuid'], 'Cancelamento por RPC');
CREATE FUNCTION pg_temp.ws(letra text DEFAULT 'a') RETURNS uuid LANGUAGE sql AS
$$ SELECT (letra || '0000000-0000-0000-0000-000000000001')::uuid $$;
CREATE FUNCTION pg_temp.m(n int) RETURNS uuid LANGUAGE sql AS
$$ SELECT ('d0000000-0000-0000-0000-' || lpad(n::text,12,'0'))::uuid $$;
GRANT EXECUTE ON FUNCTION pg_temp.ws(text), pg_temp.m(int) TO authenticated;
SELECT ok((SELECT relrowsecurity FROM pg_class WHERE oid='public.workspace_invites'::regclass), 'Convites têm RLS');
SELECT ok(NOT has_function_privilege('anon','public.team_invite(uuid,uuid,text,text,uuid)','EXECUTE'), 'anon não executa team_invite');
SELECT ok(has_function_privilege('authenticated','public.team_invite(uuid,uuid,text,text,uuid)','EXECUTE'), 'Ação de tela liberada para authenticated');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_proc p, LATERAL aclexplode(p.proacl) acl WHERE p.oid='public.team_invite(uuid,uuid,text,text,uuid)'::regprocedure AND acl.grantee=0 AND acl.privilege_type='EXECUTE'), 'PUBLIC sem EXECUTE');
SELECT ok(NOT has_function_privilege('anon','public.team_change_role(uuid,uuid,uuid,text)','EXECUTE'), 'anon não executa team_change_role');
SELECT ok(has_function_privilege('authenticated','public.team_change_role(uuid,uuid,uuid,text)','EXECUTE'), 'Ação de tela liberada para authenticated');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_proc p, LATERAL aclexplode(p.proacl) acl WHERE p.oid='public.team_change_role(uuid,uuid,uuid,text)'::regprocedure AND acl.grantee=0 AND acl.privilege_type='EXECUTE'), 'PUBLIC sem EXECUTE');
SELECT ok(NOT has_function_privilege('anon','public.team_suspend_member(uuid,uuid,uuid)','EXECUTE'), 'anon não executa team_suspend_member');
SELECT ok(has_function_privilege('authenticated','public.team_suspend_member(uuid,uuid,uuid)','EXECUTE'), 'Ação de tela liberada para authenticated');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_proc p, LATERAL aclexplode(p.proacl) acl WHERE p.oid='public.team_suspend_member(uuid,uuid,uuid)'::regprocedure AND acl.grantee=0 AND acl.privilege_type='EXECUTE'), 'PUBLIC sem EXECUTE');
SELECT ok(NOT has_function_privilege('anon','public.team_cancel_invite(uuid,uuid,uuid)','EXECUTE'), 'anon não executa team_cancel_invite');
SELECT ok(has_function_privilege('authenticated','public.team_cancel_invite(uuid,uuid,uuid)','EXECUTE'), 'Ação de tela liberada para authenticated');
SELECT ok(NOT EXISTS (SELECT 1 FROM pg_proc p, LATERAL aclexplode(p.proacl) acl WHERE p.oid='public.team_cancel_invite(uuid,uuid,uuid)'::regprocedure AND acl.grantee=0 AND acl.privilege_type='EXECUTE'), 'PUBLIC sem EXECUTE');
SELECT ok(NOT has_table_privilege('authenticated','public.workspace_members','UPDATE'), 'Papel não muda direto');
SELECT ok(NOT has_table_privilege('authenticated','public.workspace_members','DELETE'), 'Membro não é excluído direto');
SELECT ok(NOT has_table_privilege('authenticated','public.workspace_members','INSERT'), 'Membro não é criado direto');
SELECT ok(NOT has_table_privilege('authenticated','public.workspace_invites','INSERT'), 'Convites só por RPC');
SET LOCAL ROLE authenticated;
SET LOCAL "request.jwt.claims" = '{"sub":"e0000000-0000-0000-0000-000000000001","role":"authenticated"}';
SELECT lives_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(1),'teste-1-superadmin@example.test','superadmin',gen_random_uuid()) $$, 'Papel 1 convida superadmin');
SELECT lives_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(1),'teste-1-estrategista@example.test','estrategista',gen_random_uuid()) $$, 'Papel 1 convida estrategista');
SELECT lives_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(1),'teste-1-clevel@example.test','clevel',gen_random_uuid()) $$, 'Papel 1 convida clevel');
SELECT lives_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(1),'teste-1-bdr@example.test','bdr',gen_random_uuid()) $$, 'Papel 1 convida bdr');
SET LOCAL "request.jwt.claims" = '{"sub":"e0000000-0000-0000-0000-000000000002","role":"authenticated"}';
SELECT lives_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(2),'teste-2-estrategista@example.test','estrategista',gen_random_uuid()) $$, 'Papel 2 convida estrategista');
SELECT lives_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(2),'teste-2-clevel@example.test','clevel',gen_random_uuid()) $$, 'Papel 2 convida clevel');
SELECT lives_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(2),'teste-2-bdr@example.test','bdr',gen_random_uuid()) $$, 'Papel 2 convida bdr');
SET LOCAL "request.jwt.claims" = '{"sub":"e0000000-0000-0000-0000-000000000003","role":"authenticated"}';
SELECT lives_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(3),'teste-3-clevel@example.test','clevel',gen_random_uuid()) $$, 'Papel 3 convida clevel');
SELECT lives_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(3),'teste-3-bdr@example.test','bdr',gen_random_uuid()) $$, 'Papel 3 convida bdr');
SELECT is(public.team_invite(pg_temp.ws(),pg_temp.m(3),'  NORMALIZADO@Example.test ','bdr','f0000000-0000-0000-0000-000000000001')->>'email','normalizado@example.test','E-mail normalizado');
SELECT is(public.team_invite(pg_temp.ws(),pg_temp.m(3),'normalizado@example.test','bdr','f0000000-0000-0000-0000-000000000001')->>'id',
(SELECT id::text FROM public.workspace_invites WHERE email='normalizado@example.test'),'Repetir chave não duplica convite');
SELECT throws_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(3),'outro@example.test','bdr','f0000000-0000-0000-0000-000000000001') $$,'22023',NULL,'Chave não muda conteúdo');
SELECT throws_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(3),'normalizado@example.test','clevel',gen_random_uuid()) $$,'23505',NULL,'E-mail já convidado não duplica');
SELECT throws_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(3),'invalido','bdr',gen_random_uuid()) $$,'22023',NULL,'E-mail inválido');
SELECT throws_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(3),'x@example.test','owner',gen_random_uuid()) $$,'22023',NULL,'Papel inválido');
SELECT throws_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(3),'x@example.test','superadmin',gen_random_uuid()) $$,'42501',NULL,'C-level não convida superadmin');
SELECT throws_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(3),'x@example.test','estrategista',gen_random_uuid()) $$,'42501',NULL,'C-level não convida estrategista');
SELECT throws_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(3),'aline@evolut.com.br','bdr',gen_random_uuid()) $$,'23505',NULL,'Não convida membro existente');
SELECT throws_ok($$ SELECT public.team_change_role(pg_temp.ws(),pg_temp.m(3),pg_temp.m(3),'bdr') $$,'42501',NULL,'Não muda próprio papel');
SELECT throws_ok($$ SELECT public.team_change_role(pg_temp.ws(),pg_temp.m(3),pg_temp.m(4),'estrategista') $$,'42501',NULL,'Não promove acima de si');
SELECT throws_ok($$ SELECT public.team_change_role(pg_temp.ws(),pg_temp.m(3),pg_temp.m(2),'bdr') $$,'42501',NULL,'Não rebaixa superior');
SELECT throws_ok($$ SELECT public.team_suspend_member(pg_temp.ws(),pg_temp.m(3),pg_temp.m(2)) $$,'42501',NULL,'Não suspende superior');
SELECT throws_ok($$ SELECT public.team_change_role(pg_temp.ws(),pg_temp.m(3),pg_temp.m(9),'bdr') $$,'42501',NULL,'Não muda membro de outro workspace');
SELECT throws_ok($$ SELECT public.team_suspend_member(pg_temp.ws(),pg_temp.m(3),pg_temp.m(9)) $$,'42501',NULL,'Não suspende membro de outro workspace');
SELECT throws_ok($$ SELECT public.team_invite(pg_temp.ws('b'),pg_temp.m(3),'x@example.test','bdr',gen_random_uuid()) $$,'42501',NULL,'Não convida em outro workspace');
SELECT is((SELECT count(*)::int FROM public.workspace_invites WHERE workspace_id=pg_temp.ws('b')),0,'Evolut não lê convites da Grão Norte');
SELECT lives_ok($$ SELECT public.team_change_role(pg_temp.ws(),pg_temp.m(3),pg_temp.m(4),'clevel') $$,'C-level promove BDR a C-level');
SELECT is((SELECT role FROM public.workspace_members WHERE id=pg_temp.m(4)),'clevel','Papel persistido');
SELECT lives_ok($$ SELECT public.team_change_role(pg_temp.ws(),pg_temp.m(3),pg_temp.m(4),'bdr') $$,'C-level rebaixa outro C-level');
SELECT lives_ok($$ SELECT public.team_cancel_invite(pg_temp.ws(),pg_temp.m(3),(SELECT id FROM public.workspace_invites WHERE email='normalizado@example.test')) $$,'Cancela convite');
SELECT is((SELECT status FROM public.workspace_invites WHERE email='normalizado@example.test'),'canceled','Cancelamento persistido');
SELECT lives_ok($$ SELECT public.team_suspend_member(pg_temp.ws(),pg_temp.m(3),pg_temp.m(5)) $$,'Suspende outro C-level mantendo um ativo');
SET LOCAL "request.jwt.claims" = '{"sub":"e0000000-0000-0000-0000-000000000002","role":"authenticated"}';
SELECT throws_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(2),'x@example.test','superadmin',gen_random_uuid()) $$,'42501',NULL,'Estrategista não convida superadmin');
SELECT throws_ok($$ SELECT public.team_change_role(pg_temp.ws(),pg_temp.m(2),pg_temp.m(1),'bdr') $$,'42501',NULL,'Estrategista não rebaixa superadmin');
SELECT throws_ok($$ SELECT public.team_suspend_member(pg_temp.ws(),pg_temp.m(2),pg_temp.m(1)) $$,'42501',NULL,'Estrategista não suspende superadmin');
SELECT throws_ok($$ SELECT public.team_suspend_member(pg_temp.ws(),pg_temp.m(2),pg_temp.m(3)) $$,'23514',NULL,'Protege último C-level na suspensão');
SELECT throws_ok($$ SELECT public.team_change_role(pg_temp.ws(),pg_temp.m(2),pg_temp.m(3),'bdr') $$,'23514',NULL,'Protege último C-level no rebaixamento');
SELECT lives_ok($$ SELECT public.team_change_role(pg_temp.ws(),pg_temp.m(2),pg_temp.m(6),'estrategista') $$,'Estrategista promove até próprio nível');
SELECT lives_ok($$ SELECT public.team_suspend_member(pg_temp.ws(),pg_temp.m(2),pg_temp.m(6)) $$,'Estrategista suspende mesmo nível');
SET LOCAL "request.jwt.claims" = '{"sub":"e0000000-0000-0000-0000-000000000004","role":"authenticated"}';
SELECT throws_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(4),'bdr-superadmin@example.test','superadmin',gen_random_uuid()) $$,'42501',NULL,'BDR não convida superadmin');
SELECT throws_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(4),'bdr-estrategista@example.test','estrategista',gen_random_uuid()) $$,'42501',NULL,'BDR não convida estrategista');
SELECT throws_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(4),'bdr-clevel@example.test','clevel',gen_random_uuid()) $$,'42501',NULL,'BDR não convida clevel');
SELECT throws_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(4),'bdr-bdr@example.test','bdr',gen_random_uuid()) $$,'42501',NULL,'BDR não convida bdr');
SELECT throws_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(3),'x@example.test','bdr',gen_random_uuid()) $$,'42501',NULL,'Não se passa pelo C-level');
SELECT throws_ok($$ SELECT public.team_change_role(pg_temp.ws(),pg_temp.m(3),pg_temp.m(6),'bdr') $$,'42501',NULL,'Não muda papel em nome alheio');
SELECT throws_ok($$ SELECT public.team_suspend_member(pg_temp.ws(),pg_temp.m(3),pg_temp.m(6)) $$,'42501',NULL,'Não suspende em nome alheio');
SELECT throws_ok($$ SELECT public.team_change_role(pg_temp.ws(),pg_temp.m(4),pg_temp.m(6),'bdr') $$,'42501',NULL,'BDR não muda papel');
SELECT throws_ok($$ SELECT public.team_suspend_member(pg_temp.ws(),pg_temp.m(4),pg_temp.m(6)) $$,'42501',NULL,'BDR não suspende');
SELECT throws_ok($$ UPDATE public.workspace_members SET role='superadmin' WHERE id=pg_temp.m(4) $$,'42501',NULL,'Tabela não permite autoelevação');
SET LOCAL "request.jwt.claims" = '{"sub":"e0000000-0000-0000-0000-000000000007","role":"authenticated"}';
SELECT is((SELECT count(*)::int FROM public.workspace_invites),0,'Grão Norte não lê convites Evolut');
SELECT lives_ok($$ SELECT public.team_invite(pg_temp.ws('b'),pg_temp.m(9),'grao@example.test','bdr',gen_random_uuid()) $$,'Grão Norte cria próprio convite');
SELECT throws_ok($$ SELECT public.team_cancel_invite(pg_temp.ws(),pg_temp.m(9),'f0000000-0000-0000-0000-000000000001') $$,'42501',NULL,'Grão Norte não cancela convite Evolut');
SET LOCAL "request.jwt.claims" = '{"sub":"e0000000-0000-0000-0000-000000000001","role":"authenticated"}';
SELECT lives_ok($$ SELECT public.team_change_role(pg_temp.ws(),pg_temp.m(1),pg_temp.m(2),'superadmin') $$,'Superadmin promove até próprio nível');
SELECT lives_ok($$ SELECT public.team_suspend_member(pg_temp.ws(),pg_temp.m(1),pg_temp.m(2)) $$,'Superadmin suspende mesmo nível');
SET LOCAL "request.jwt.claims" = '{"sub":"e0000000-0000-0000-0000-000000000002","role":"authenticated"}';
SELECT throws_ok($$ SELECT public.team_invite(pg_temp.ws(),pg_temp.m(2),'suspenso@example.test','bdr',gen_random_uuid()) $$,'42501',NULL,'Membro suspenso perde acesso imediatamente');
RESET ROLE;
SELECT is((SELECT count(*)::int FROM public.audit_logs WHERE action='membro.papel_mudado' AND entity_id=pg_temp.m(4)),2,'Mudanças auditadas uma vez por mudança');
SELECT ok(EXISTS(SELECT 1 FROM public.audit_logs WHERE action='membro.papel_mudado' AND entity_id=pg_temp.m(4) AND workspace_id=pg_temp.ws() AND actor_member_id=pg_temp.m(3) AND new_values->>'papel_anterior'='bdr' AND new_values->>'papel_novo'='clevel'),'Auditoria identifica autor, workspace e mudança');
SELECT is((SELECT role FROM public.workspace_members WHERE id=pg_temp.m(9)),'clevel','Grão Norte permanece intacta');
SELECT is((SELECT count(*)::int FROM public.workspace_members WHERE workspace_id=pg_temp.ws() AND status='active' AND role='clevel'),1,'Último C-level continua ativo');
SELECT * FROM finish();
ROLLBACK;
